site_name: CS1101S Sample PA Solutions
site_description: Solution code organised by practice and question
site_url: https://eddrick-23.github.io/CS1101S/
repo_url: https://github.com/Eddrick-23/CS1101S
repo_name: Eddrick-23/CS1101S

docs_dir: docs

hooks:
  - hooks.py

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
